services:
  db:
    image: mysql:8
    container_name: dit312final_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: movies_db
    ports:
      - "3306:3306"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - dit312final_mysql_data:/var/lib/mysql

  api:
    build:
      context: ./backend
    container_name: dit312final_api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: dit312final_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  dit312final_mysql_data:
